project_id = "svbqnwchxrvydtxmnnsd"

[functions.analyze-submission]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.generate-zip]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.process-document]
verify_jwt = false
